#ifndef WEB_DASHBOARD_HTML_H
#define WEB_DASHBOARD_HTML_H

// Inbäddad HTML/CSS/JS frontend för lokal odlingsövervakning
static const char WEB_DASHBOARD_HTML[] = 
"<!DOCTYPE html>"
"<html>"
"<head>"
"<meta charset='utf-8'/>"
"<meta name='viewport' content='width=device-width, initial-scale=1'/>"
"<title>HydroGreen - MicroHydros Dashboard</title>"
"<style>"
"body{font-family:sans-serif;background:#12181f;color:#e1e7ec;margin:0;padding:20px;text-align:center}"
"h1{color:#4caf50;margin-bottom:5px}"
".grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:15px;max-width:800px;margin:20px auto}"
".card{background:#1e293b;padding:20px;border-radius:12px;box-shadow:0 4px 6px rgba(0,0,0,0.3)}"
".val{font-size:2em;font-weight:bold;color:#38bdf8;margin:10px 0}"
".unit{font-size:0.5em;color:#94a3b8}"
".badge{display:inline-block;padding:4px 12px;border-radius:20px;font-weight:bold;background:#22c55e;color:#000}"
"</style>"
"</head>"
"<body>"
"<h1>🌱 MicroHydros Live Dashboard</h1>"
"<p>Hydroponisk miljöövervakning i realtid</p>"
"<div class='grid'>"
"<div class='card'><h3>Inneluft</h3><div class='val' id='ti'>--<span class='unit'> °C</span></div></div>"
"<div class='card'><h3>Luftfuktighet</h3><div class='val' id='hi'>--<span class='unit'> %</span></div></div>"
"<div class='card'><h3>Vattentemperatur</h3><div class='val' id='tw'>--<span class='unit'> °C</span></div></div>"
"<div class='card'><h3>Utetemperatur</h3><div class='val' id='to'>--<span class='unit'> °C</span></div></div>"
"</div>"
"<div>Larmstatus: <span id='alarm' class='badge'>NORMAL</span></div>"
"<script>"
"async function poll(){"
"try{"
"const r=await fetch('/api/sensors');"
"const d=await r.json();"
"document.getElementById('ti').innerText=d.temp_inside.toFixed(1);"
"document.getElementById('hi').innerText=d.humidity.toFixed(1);"
"document.getElementById('tw').innerText=d.temp_water.toFixed(1);"
"document.getElementById('to').innerText=d.temp_outside.toFixed(1);"
"document.getElementById('alarm').innerText=d.alarm;"
"}catch(e){console.error(e);}"
"}"
"setInterval(poll, 2000); poll();"
"</script>"
"</body>"
"</html>";

#endif // WEB_DASHBOARD_HTML_H
