#ifndef WEB_DASHBOARD_HTML_H
#define WEB_DASHBOARD_HTML_H

// Inbäddad HTML/CSS/JS frontend för lokal odlingsövervakning
static const char WEB_DASHBOARD_HTML[] = 
"<!DOCTYPE html>\n"
"<html lang=\"sv\">\n"
"<head>\n"
"<meta charset=\"utf-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"<title>HydroGreen - MicroHydros Dashboard</title>\n"
"<style>\n"
"@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&family=VT323&display=swap');\n"
"\n"
"*{box-sizing:border-box}\n"
"html,body{min-height:100%}\n"
"\n"
"body{\n"
"  margin:0;\n"
"  min-height:100vh;\n"
"  overflow-x:hidden;\n"
"  padding:58px 24px 34px;\n"
"  font-family:\"Poppins\",sans-serif;\n"
"  color:#fff;\n"
"  text-align:center;\n"
"  background:#08090b;\n"
"  position:relative;\n"
"}\n"
"\n"
"body::before{\n"
"  content:\"\";\n"
"  position:fixed;\n"
"  inset:0;\n"
"  pointer-events:none;\n"
"  z-index:0;\n"
"  background:\n"
"    radial-gradient(ellipse 900px 500px at 50% 0%, rgba(255,255,255,.09), transparent 60%),\n"
"    radial-gradient(circle at 50% 35%,rgba(255,255,255,.05),transparent 40%),\n"
"    linear-gradient(180deg,rgba(0,0,0,.15),rgba(0,0,0,.35) 45%,rgba(0,0,0,.55));\n"
"}\n"
"\n"
"body>*{position:relative;z-index:1}\n"
"\n"
".pill{\n"
"  display:inline-block;\n"
"  margin:0 0 18px;\n"
"  padding:7px 17px;\n"
"  border-radius:999px;\n"
"  border:1px solid rgba(255,255,255,.15);\n"
"  background:rgba(255,255,255,.03);\n"
"  -webkit-backdrop-filter:blur(10px);\n"
"  backdrop-filter:blur(10px);\n"
"  color:rgba(255,255,255,.88);\n"
"  font-size:.78rem;\n"
"  font-weight:600;\n"
"  letter-spacing:.08em;\n"
"  text-transform:uppercase;\n"
"  text-shadow:0 0 5px rgba(255,255,255,.35);\n"
"}\n"
"\n"
"h1 {\n"
"  margin: 2rem 0;\n"
"  color: #fff;\n"
"  font-family: \"Poppins\", sans-serif;\n"
"  font-size: clamp(2.3rem, 5.5vw, 4.1rem);\n"
"  font-weight: 500;\n"
"  line-height: 1.08;\n"
"  letter-spacing: -0.03em;\n"
"  text-wrap: balance;\n"
"  text-shadow: 0 4px 24px rgba(0, 0, 0, 0.5);\n"
"  -webkit-font-smoothing: antialiased;\n"
"  text-rendering: optimizeLegibility;\n"
"}\n"
"\n"
"p.sub{\n"
"  max-width:700px;\n"
"  margin:18px auto 34px;\n"
"  color:rgba(255,255,255,.78);\n"
"  font-size:.98rem;\n"
"  line-height:1.7;\n"
"  text-shadow:0 0 5px rgba(255,255,255,.28),0 3px 15px rgba(0,0,0,.6);\n"
"}\n"
"\n"
".grid{\n"
"  display:grid;\n"
"  grid-template-columns:repeat(4,minmax(0,1fr));\n"
"  gap:16px;\n"
"  max-width:1000px;\n"
"  margin:0 auto 28px;\n"
"}\n"
"\n"
".card{\n"
"  padding:12px 18px;\n"
"}\n"
"\n"
".label{\n"
"  margin-bottom:8px;\n"
"  color:rgba(255,255,255,.68);\n"
"  font-size:.74rem;\n"
"  font-weight:600;\n"
"  letter-spacing:.12em;\n"
"  text-transform:uppercase;\n"
"  text-shadow:0 0 5px rgba(255,255,255,.28);\n"
"}\n"
"\n"
".val{\n"
"  margin:0;\n"
"  color:#fff;\n"
"  font-family:\"VT323\",monospace;\n"
"  font-size:3rem;\n"
"  line-height:1;\n"
"  text-shadow:0 0 7px rgba(255,255,255,.45),0 4px 18px rgba(0,0,0,.5);\n"
"}\n"
"\n"
".unit{\n"
"  color:rgba(255,255,255,.72);\n"
"  font-family:\"Poppins\",sans-serif;\n"
"  font-size:.34em;\n"
"  font-weight:500;\n"
"}\n"
"\n"
".status-row{\n"
"  display:flex;\n"
"  align-items:center;\n"
"  justify-content:center;\n"
"  gap:10px;\n"
"  margin:0 auto 26px;\n"
"}\n"
"\n"
".dot{\n"
"  width:9px;\n"
"  height:9px;\n"
"  border-radius:50%;\n"
"  background:#62ffad;\n"
"  box-shadow:0 0 12px #62ffad,0 0 24px rgba(98,255,173,.45);\n"
"  animation:pulse 2s infinite;\n"
"}\n"
"\n"
".badge{\n"
"  display:inline-block;\n"
"  padding:5px 15px;\n"
"  border:1px solid rgba(98,255,173,.5);\n"
"  border-radius:999px;\n"
"  background:rgba(98,255,173,.08);\n"
"  color:#a8ffd1;\n"
"  font-size:.78rem;\n"
"  font-weight:700;\n"
"  letter-spacing:.08em;\n"
"  text-shadow:0 0 5px rgba(255,255,255,.3);\n"
"  box-shadow:0 0 18px rgba(98,255,173,.08),inset 0 1px 0 rgba(255,255,255,.1);\n"
"}\n"
"\n"
".badge.alert{\n"
"  border-color:rgba(255,130,130,.65);\n"
"  background:rgba(255,80,80,.10);\n"
"  color:#ffb0b0;\n"
"}\n"
"\n"
".sources{\n"
"  display:flex;\n"
"  flex-wrap:wrap;\n"
"  justify-content:center;\n"
"  gap:12px 25px;\n"
"  max-width:1000px;\n"
"  margin:0 auto;\n"
"  padding-top:20px;\n"
"  border-top:1px solid rgba(255,255,255,.08);\n"
"  color:rgba(255,255,255,.62);\n"
"  font-size:.76rem;\n"
"  text-shadow:0 0 5px rgba(255,255,255,.22),0 2px 10px rgba(0,0,0,.55);\n"
"}\n"
"\n"
".sources span{display:flex;align-items:center;gap:6px}\n"
"\n"
"a{\n"
"  color:#fff;\n"
"  font-weight:700;\n"
"  text-decoration:none;\n"
"  text-shadow:0 0 5px rgba(255,255,255,.5);\n"
"}\n"
"\n"
"@keyframes pulse{0%,100%{opacity:1}50%{opacity:.35}}\n"
"\n"
"@media (max-width:760px){\n"
"  body{padding:42px 16px 28px}\n"
"  .grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}\n"
"  .card{padding:20px 12px}\n"
"}\n"
"\n"
"@media (max-width:430px){\n"
"  .grid{grid-template-columns:1fr}\n"
"  h1{font-size:2.5rem}\n"
"  p.sub{font-size:.9rem;margin-bottom:28px}\n"
"  .val{font-size:2.8rem}\n"
"}\n"
"\n"
"@media (prefers-reduced-motion:reduce){\n"
"  *,*::before,*::after{animation:none!important;transition:none!important}\n"
"}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<div class=\"pill\">🌱 Byggd för Odling</div>\n"
"<h1>Varje Mätning.<br>Varje Ögonblick.</h1>\n"
"<p class=\"sub\">Missa aldrig en avvikelse. Systemet övervakar klimatet i din hydroponiska odling kontinuerligt och flaggar direkt om något avviker.</p>\n"
"<div class=\"grid\">\n"
"<div class=\"card\"><div class=\"label\">Inneluft</div><div class=\"val\" id=\"ti\">--<span class=\"unit\"> °C</span></div></div>\n"
"<div class=\"card\"><div class=\"label\">Luftfuktighet</div><div class=\"val\" id=\"hi\">--<span class=\"unit\"> %</span></div></div>\n"
"<div class=\"card\"><div class=\"label\">Vattentemperatur</div><div class=\"val\" id=\"tw\">--<span class=\"unit\"> °C</span></div></div>\n"
"<div class=\"card\"><div class=\"label\">Utetemperatur</div><div class=\"val\" id=\"to\">--<span class=\"unit\"> °C</span></div></div>\n"
"</div>\n"
"<div class=\"status-row\"><span class=\"dot\"></span><span id=\"alarm\" class=\"badge\">NORMAL</span></div>\n"
"<div class=\"sources\"><span>📡 BME280</span><span>🌡️ DS18B20 x2</span><span>📶 MQTT</span><span>⚙️ ESP32-S3</span></div>\n"
"<script>\n"
"async function poll(){\n"
"try{\n"
"const r=await fetch('/api/sensors');\n"
"const d=await r.json();\n"
"document.getElementById('ti').innerHTML=d.temp_inside.toFixed(1)+\"<span class='unit'> °C</span>\";\n"
"document.getElementById('hi').innerHTML=d.humidity.toFixed(1)+\"<span class='unit'> %</span>\";\n"
"document.getElementById('tw').innerHTML=d.temp_water.toFixed(1)+\"<span class='unit'> °C</span>\";\n"
"document.getElementById('to').innerHTML=d.temp_outside.toFixed(1)+\"<span class='unit'> °C</span>\";\n"
"const badge=document.getElementById('alarm');\n"
"badge.innerText=d.alarm;\n"
"badge.className=(d.alarm==='NORMAL')?'badge':'badge alert';\n"
"}catch(e){console.error(e);}\n"
"}\n"
"setInterval(poll,2000);poll();\n"
"</script>\n"
"\n"
"<script>\n"
"/** @license\n"
" * DHTML Snowstorm! JavaScript-based snow for web pages\n"
" * Making it snow on the internets since 2003. You're welcome.\n"
" * -----------------------------------------------------------\n"
" * Version 1.44.20131208 (Previous rev: 1.44.20131125)\n"
" * Copyright (c) 2007, Scott Schiller. All rights reserved.\n"
" * Code provided under the BSD License\n"
" * http://schillmania.com/projects/snowstorm/license.txt\n"
" */\n"
"\n"
"/*jslint nomen: true, plusplus: true, sloppy: true, vars: true, white: true */\n"
"/*global window, document, navigator, clearInterval, setInterval */\n"
"\n"
"var snowStorm = (function(window, document) {\n"
"\n"
"    // --- common properties ---\n"
"\n"
"    this.autoStart = true;\n"
"    this.excludeMobile = true;\n"
"    this.flakesMax = 32;\n"
"    this.flakesMaxActive = 32;\n"
"    this.animationInterval = 33;\n"
"    this.useGPU = true;\n"
"    this.className = null;\n"
"    this.excludeMobile = true;\n"
"    this.flakeBottom = null;\n"
"    this.followMouse = true;\n"
"    this.snowColor = '#FFFFFF';\n"
"    this.snowCharacter = '&bull;';\n"
"    this.snowStick = true;\n"
"    this.targetElement = null;\n"
"    this.useMeltEffect = true;\n"
"    this.useTwinkleEffect = true;\n"
"    this.usePositionFixed = false;\n"
"    this.usePixelPosition = false;\n"
"\n"
"    this.freezeOnBlur = true;\n"
"    this.flakeLeftOffset = 0;\n"
"    this.flakeRightOffset = 0;\n"
"    this.flakeWidth = 8;\n"
"    this.flakeHeight = 8;\n"
"    this.vMaxX = 5;\n"
"    this.vMaxY = 4;\n"
"    this.zIndex = 0;\n"
"\n"
"    var storm = this,\n"
"    features,\n"
"    isIE = navigator.userAgent.match(/msie/i),\n"
"    isIE6 = navigator.userAgent.match(/msie 6/i),\n"
"    isMobile = navigator.userAgent.match(/mobile|opera m(ob|in)/i),\n"
"    isBackCompatIE = (isIE && document.compatMode === 'BackCompat'),\n"
"    noFixed = (isBackCompatIE || isIE6),\n"
"    screenX = null, screenX2 = null, screenY = null, scrollY = null, docHeight = null, vRndX = null, vRndY = null,\n"
"    windOffset = 1,\n"
"    windMultiplier = 2,\n"
"    flakeTypes = 6,\n"
"    fixedForEverything = false,\n"
"    targetElementIsRelative = false,\n"
"    opacitySupported = (function(){\n"
"      try {\n"
"        document.createElement('div').style.opacity = '0.5';\n"
"      } catch(e) {\n"
"        return false;\n"
"      }\n"
"      return true;\n"
"    }()),\n"
"    didInit = false,\n"
"    docFrag = document.createDocumentFragment();\n"
"\n"
"    features = (function() {\n"
"\n"
"      var getAnimationFrame;\n"
"\n"
"      function timeoutShim(callback) {\n"
"        window.setTimeout(callback, 1000/(storm.animationInterval || 20));\n"
"      }\n"
"\n"
"      var _animationFrame = (window.requestAnimationFrame ||\n"
"          window.webkitRequestAnimationFrame ||\n"
"          window.mozRequestAnimationFrame ||\n"
"          window.oRequestAnimationFrame ||\n"
"          window.msRequestAnimationFrame ||\n"
"          timeoutShim);\n"
"\n"
"      getAnimationFrame = _animationFrame ? function() {\n"
"        return _animationFrame.apply(window, arguments);\n"
"      } : null;\n"
"\n"
"      var testDiv;\n"
"\n"
"      testDiv = document.createElement('div');\n"
"\n"
"      function has(prop) {\n"
"        var result = testDiv.style[prop];\n"
"        return (result !== undefined ? prop : null);\n"
"      }\n"
"\n"
"      var localFeatures = {\n"
"\n"
"        transform: {\n"
"          ie:  has('-ms-transform'),\n"
"          moz: has('MozTransform'),\n"
"          opera: has('OTransform'),\n"
"          webkit: has('webkitTransform'),\n"
"          w3: has('transform'),\n"
"          prop: null\n"
"        },\n"
"\n"
"        getAnimationFrame: getAnimationFrame\n"
"\n"
"      };\n"
"\n"
"      localFeatures.transform.prop = (\n"
"        localFeatures.transform.w3 || \n"
"        localFeatures.transform.moz ||\n"
"        localFeatures.transform.webkit ||\n"
"        localFeatures.transform.ie ||\n"
"        localFeatures.transform.opera\n"
"      );\n"
"\n"
"      testDiv = null;\n"
"\n"
"      return localFeatures;\n"
"\n"
"    }());\n"
"\n"
"    this.timer = null;\n"
"    this.flakes = [];\n"
"    this.disabled = false;\n"
"    this.active = false;\n"
"    this.meltFrameCount = 20;\n"
"    this.meltFrames = [];\n"
"\n"
"    this.setXY = function(o, x, y) {\n"
"\n"
"      if (!o) {\n"
"        return false;\n"
"      }\n"
"\n"
"      if (storm.usePixelPosition || targetElementIsRelative) {\n"
"\n"
"        o.style.left = (x - storm.flakeWidth) + 'px';\n"
"        o.style.top = (y - storm.flakeHeight) + 'px';\n"
"\n"
"      } else if (noFixed) {\n"
"\n"
"        o.style.right = (100-(x/screenX*100)) + '%';\n"
"        o.style.top = (Math.min(y, docHeight-storm.flakeHeight)) + 'px';\n"
"\n"
"      } else {\n"
"\n"
"        if (!storm.flakeBottom) {\n"
"\n"
"          o.style.right = (100-(x/screenX*100)) + '%';\n"
"          o.style.bottom = (100-(y/screenY*100)) + '%';\n"
"\n"
"        } else {\n"
"\n"
"          o.style.right = (100-(x/screenX*100)) + '%';\n"
"          o.style.top = (Math.min(y, docHeight-storm.flakeHeight)) + 'px';\n"
"\n"
"        }\n"
"\n"
"      }\n"
"\n"
"    };\n"
"\n"
"    this.events = (function() {\n"
"\n"
"      var old = (!window.addEventListener && window.attachEvent), slice = Array.prototype.slice,\n"
"      evt = {\n"
"        add: (old?'attachEvent':'addEventListener'),\n"
"        remove: (old?'detachEvent':'removeEventListener')\n"
"      };\n"
"\n"
"      function getArgs(oArgs) {\n"
"        var args = slice.call(oArgs), len = args.length;\n"
"        if (old) {\n"
"          args[1] = 'on' + args[1];\n"
"          if (len > 3) {\n"
"            args.pop();\n"
"          }\n"
"        } else if (len === 3) {\n"
"          args.push(false);\n"
"        }\n"
"        return args;\n"
"      }\n"
"\n"
"      function apply(args, sType) {\n"
"        var element = args.shift(),\n"
"            method = [evt[sType]];\n"
"        if (old) {\n"
"          element[method](args[0], args[1]);\n"
"        } else {\n"
"          element[method].apply(element, args);\n"
"        }\n"
"      }\n"
"\n"
"      function addEvent() {\n"
"        apply(getArgs(arguments), 'add');\n"
"      }\n"
"\n"
"      function removeEvent() {\n"
"        apply(getArgs(arguments), 'remove');\n"
"      }\n"
"\n"
"      return {\n"
"        add: addEvent,\n"
"        remove: removeEvent\n"
"      };\n"
"\n"
"    }());\n"
"\n"
"    function rnd(n,min) {\n"
"      if (isNaN(min)) {\n"
"        min = 0;\n"
"      }\n"
"      return (Math.random()*n)+min;\n"
"    }\n"
"\n"
"    function plusMinus(n) {\n"
"      return (parseInt(rnd(2),10)===1?n*-1:n);\n"
"    }\n"
"\n"
"    this.randomizeWind = function() {\n"
"      var i;\n"
"      vRndX = plusMinus(rnd(storm.vMaxX,0.2));\n"
"      vRndY = rnd(storm.vMaxY,0.2);\n"
"      if (this.flakes) {\n"
"        for (i=0; i<this.flakes.length; i++) {\n"
"          if (this.flakes[i].active) {\n"
"            this.flakes[i].setVelocities();\n"
"          }\n"
"        }\n"
"      }\n"
"    };\n"
"\n"
"    this.scrollHandler = function() {\n"
"      var i;\n"
"      scrollY = (storm.flakeBottom ? 0 : parseInt(window.scrollY || document.documentElement.scrollTop || (noFixed ? document.body.scrollTop : 0), 10));\n"
"      if (isNaN(scrollY)) {\n"
"        scrollY = 0;\n"
"      }\n"
"      if (!fixedForEverything && !storm.flakeBottom && storm.flakes) {\n"
"        for (i=0; i<storm.flakes.length; i++) {\n"
"          if (storm.flakes[i].active === 0) {\n"
"            storm.flakes[i].stick();\n"
"          }\n"
"        }\n"
"      }\n"
"    };\n"
"\n"
"    this.resizeHandler = function() {\n"
"      if (window.innerWidth || window.innerHeight) {\n"
"        screenX = window.innerWidth - 16 - storm.flakeRightOffset;\n"
"        screenY = (storm.flakeBottom || window.innerHeight);\n"
"      } else {\n"
"        screenX = (document.documentElement.clientWidth || document.body.clientWidth || document.body.scrollWidth) - (!isIE ? 8 : 0) - storm.flakeRightOffset;\n"
"        screenY = storm.flakeBottom || document.documentElement.clientHeight || document.body.clientHeight || document.body.scrollHeight;\n"
"      }\n"
"      docHeight = document.body.offsetHeight;\n"
"      screenX2 = parseInt(screenX/2,10);\n"
"    };\n"
"\n"
"    this.resizeHandlerAlt = function() {\n"
"      screenX = storm.targetElement.offsetWidth - storm.flakeRightOffset;\n"
"      screenY = storm.flakeBottom || storm.targetElement.offsetHeight;\n"
"      screenX2 = parseInt(screenX/2,10);\n"
"      docHeight = document.body.offsetHeight;\n"
"    };\n"
"\n"
"    this.freeze = function() {\n"
"      if (!storm.disabled) {\n"
"        storm.disabled = 1;\n"
"      } else {\n"
"        return false;\n"
"      }\n"
"      storm.timer = null;\n"
"    };\n"
"\n"
"    this.resume = function() {\n"
"      if (storm.disabled) {\n"
"         storm.disabled = 0;\n"
"      } else {\n"
"        return false;\n"
"      }\n"
"      storm.timerInit();\n"
"    };\n"
"\n"
"    this.toggleSnow = function() {\n"
"      if (!storm.flakes.length) {\n"
"        storm.start();\n"
"      } else {\n"
"        storm.active = !storm.active;\n"
"        if (storm.active) {\n"
"          storm.show();\n"
"          storm.resume();\n"
"        } else {\n"
"          storm.stop();\n"
"          storm.freeze();\n"
"        }\n"
"      }\n"
"    };\n"
"\n"
"    this.stop = function() {\n"
"      var i;\n"
"      this.freeze();\n"
"      for (i=0; i<this.flakes.length; i++) {\n"
"        this.flakes[i].o.style.display = 'none';\n"
"      }\n"
"      storm.events.remove(window,'scroll',storm.scrollHandler);\n"
"      storm.events.remove(window,'resize',storm.resizeHandler);\n"
"      if (storm.freezeOnBlur) {\n"
"        if (isIE) {\n"
"          storm.events.remove(document,'focusout',storm.freeze);\n"
"          storm.events.remove(document,'focusin',storm.resume);\n"
"        } else {\n"
"          storm.events.remove(window,'blur',storm.freeze);\n"
"          storm.events.remove(window,'focus',storm.resume);\n"
"        }\n"
"      }\n"
"    };\n"
"\n"
"    this.show = function() {\n"
"      var i;\n"
"      for (i=0; i<this.flakes.length; i++) {\n"
"        this.flakes[i].o.style.display = 'block';\n"
"      }\n"
"    };\n"
"\n"
"    this.SnowFlake = function(type,x,y) {\n"
"      var s = this;\n"
"      this.type = type;\n"
"      this.x = x||parseInt(rnd(screenX-20),10);\n"
"      this.y = (!isNaN(y)?y:-rnd(screenY)-12);\n"
"      this.vX = null;\n"
"      this.vY = null;\n"
"      this.vAmpTypes = [1,1.2,1.4,1.6,1.8];\n"
"      this.vAmp = this.vAmpTypes[this.type] || 1;\n"
"      this.melting = false;\n"
"      this.meltFrameCount = storm.meltFrameCount;\n"
"      this.meltFrames = storm.meltFrames;\n"
"      this.meltFrame = 0;\n"
"      this.twinkleFrame = 0;\n"
"      this.active = 1;\n"
"      this.fontSize = (10+(this.type/5)*10);\n"
"      this.o = document.createElement('div');\n"
"      this.o.innerHTML = storm.snowCharacter;\n"
"      if (storm.className) {\n"
"        this.o.setAttribute('class', storm.className);\n"
"      }\n"
"      this.o.style.color = storm.snowColor;\n"
"      this.o.style.position = (fixedForEverything?'fixed':'absolute');\n"
"      if (storm.useGPU && features.transform.prop) {\n"
"        this.o.style[features.transform.prop] = 'translate3d(0px, 0px, 0px)';\n"
"      }\n"
"      this.o.style.width = storm.flakeWidth+'px';\n"
"      this.o.style.height = storm.flakeHeight+'px';\n"
"      this.o.style.fontFamily = 'arial,verdana';\n"
"      this.o.style.cursor = 'default';\n"
"      this.o.style.overflow = 'hidden';\n"
"      this.o.style.fontWeight = 'normal';\n"
"      this.o.style.zIndex = storm.zIndex;\n"
"      docFrag.appendChild(this.o);\n"
"\n"
"      this.refresh = function() {\n"
"        if (isNaN(s.x) || isNaN(s.y)) {\n"
"          return false;\n"
"        }\n"
"        storm.setXY(s.o, s.x, s.y);\n"
"      };\n"
"\n"
"      this.stick = function() {\n"
"        if (noFixed || (storm.targetElement !== document.documentElement && storm.targetElement !== document.body)) {\n"
"          s.o.style.top = (screenY+scrollY-storm.flakeHeight)+'px';\n"
"        } else if (storm.flakeBottom) {\n"
"          s.o.style.top = storm.flakeBottom+'px';\n"
"        } else {\n"
"          s.o.style.display = 'none';\n"
"          s.o.style.bottom = '0%';\n"
"          s.o.style.position = 'fixed';\n"
"          s.o.style.display = 'block';\n"
"        }\n"
"      };\n"
"\n"
"      this.vCheck = function() {\n"
"        if (s.vX>=0 && s.vX<0.2) {\n"
"          s.vX = 0.2;\n"
"        } else if (s.vX<0 && s.vX>-0.2) {\n"
"          s.vX = -0.2;\n"
"        }\n"
"        if (s.vY>=0 && s.vY<0.2) {\n"
"          s.vY = 0.2;\n"
"        }\n"
"      };\n"
"\n"
"      this.move = function() {\n"
"        var vX = s.vX*windOffset, yDiff;\n"
"        s.x += vX;\n"
"        s.y += (s.vY*s.vAmp);\n"
"        if (s.x >= screenX || screenX-s.x < storm.flakeWidth) {\n"
"          s.x = 0;\n"
"        } else if (vX < 0 && s.x-storm.flakeLeftOffset < -storm.flakeWidth) {\n"
"          s.x = screenX-storm.flakeWidth-1;\n"
"        }\n"
"        s.refresh();\n"
"        yDiff = screenY+scrollY-s.y+storm.flakeHeight;\n"
"        if (yDiff<storm.flakeHeight) {\n"
"          s.active = 0;\n"
"          if (storm.snowStick) {\n"
"            s.stick();\n"
"          } else {\n"
"            s.recycle();\n"
"          }\n"
"        } else {\n"
"          if (storm.useMeltEffect && s.active && s.type < 3 && !s.melting && Math.random()>0.998) {\n"
"            s.melting = true;\n"
"            s.melt();\n"
"          }\n"
"          if (storm.useTwinkleEffect) {\n"
"            if (s.twinkleFrame < 0) {\n"
"              if (Math.random() > 0.97) {\n"
"                s.twinkleFrame = parseInt(Math.random() * 8, 10);\n"
"              }\n"
"            } else {\n"
"              s.twinkleFrame--;\n"
"              if (!opacitySupported) {\n"
"                s.o.style.visibility = (s.twinkleFrame && s.twinkleFrame % 2 === 0 ? 'hidden' : 'visible');\n"
"              } else {\n"
"                s.o.style.opacity = (s.twinkleFrame && s.twinkleFrame % 2 === 0 ? 0 : 1);\n"
"              }\n"
"            }\n"
"          }\n"
"        }\n"
"      };\n"
"\n"
"      this.animate = function() {\n"
"        s.move();\n"
"      };\n"
"\n"
"      this.setVelocities = function() {\n"
"        s.vX = vRndX+rnd(storm.vMaxX*0.12,0.1);\n"
"        s.vY = vRndY+rnd(storm.vMaxY*0.12,0.1);\n"
"      };\n"
"\n"
"      this.setOpacity = function(o,opacity) {\n"
"        if (!opacitySupported) {\n"
"          return false;\n"
"        }\n"
"        o.style.opacity = opacity;\n"
"      };\n"
"\n"
"      this.melt = function() {\n"
"        if (!storm.useMeltEffect || !s.melting) {\n"
"          s.recycle();\n"
"        } else {\n"
"          if (s.meltFrame < s.meltFrameCount) {\n"
"            s.setOpacity(s.o,s.meltFrames[s.meltFrame]);\n"
"            s.o.style.fontSize = s.fontSize-(s.fontSize*(s.meltFrame/s.meltFrameCount))+'px';\n"
"            s.o.style.lineHeight = storm.flakeHeight+2+(storm.flakeHeight*0.75*(s.meltFrame/s.meltFrameCount))+'px';\n"
"            s.meltFrame++;\n"
"          } else {\n"
"            s.recycle();\n"
"          }\n"
"        }\n"
"      };\n"
"\n"
"      this.recycle = function() {\n"
"        s.o.style.display = 'none';\n"
"        s.o.style.position = (fixedForEverything?'fixed':'absolute');\n"
"        s.o.style.bottom = 'auto';\n"
"        s.setVelocities();\n"
"        s.vCheck();\n"
"        s.meltFrame = 0;\n"
"        s.melting = false;\n"
"        s.setOpacity(s.o,1);\n"
"        s.o.style.padding = '0px';\n"
"        s.o.style.margin = '0px';\n"
"        s.o.style.fontSize = s.fontSize+'px';\n"
"        s.o.style.lineHeight = (storm.flakeHeight+2)+'px';\n"
"        s.o.style.textAlign = 'center';\n"
"        s.o.style.verticalAlign = 'baseline';\n"
"        s.x = parseInt(rnd(screenX-storm.flakeWidth-20),10);\n"
"        s.y = parseInt(rnd(screenY)*-1,10)-storm.flakeHeight;\n"
"        s.refresh();\n"
"        s.o.style.display = 'block';\n"
"        s.active = 1;\n"
"      };\n"
"\n"
"      this.recycle();\n"
"      this.refresh();\n"
"\n"
"    };\n"
"\n"
"    this.snow = function() {\n"
"      var active = 0, flake = null, i, j;\n"
"      for (i=0, j=storm.flakes.length; i<j; i++) {\n"
"        if (storm.flakes[i].active === 1) {\n"
"          storm.flakes[i].move();\n"
"          active++;\n"
"        }\n"
"        if (storm.flakes[i].melting) {\n"
"          storm.flakes[i].melt();\n"
"        }\n"
"      }\n"
"      if (active<storm.flakesMaxActive) {\n"
"        flake = storm.flakes[parseInt(rnd(storm.flakes.length),10)];\n"
"        if (flake.active === 0) {\n"
"          flake.melting = true;\n"
"        }\n"
"      }\n"
"      if (storm.timer) {\n"
"        features.getAnimationFrame(storm.snow);\n"
"      }\n"
"    };\n"
"\n"
"    this.mouseMove = function(e) {\n"
"      if (!storm.followMouse) {\n"
"        return true;\n"
"      }\n"
"      var x = parseInt(e.clientX,10);\n"
"      if (x<screenX2) {\n"
"        windOffset = -windMultiplier+(x/screenX2*windMultiplier);\n"
"      } else {\n"
"        x -= screenX2;\n"
"        windOffset = (x/screenX2)*windMultiplier;\n"
"      }\n"
"    };\n"
"\n"
"    this.createSnow = function(limit,allowInactive) {\n"
"      var i;\n"
"      for (i=0; i<limit; i++) {\n"
"        storm.flakes[storm.flakes.length] = new storm.SnowFlake(parseInt(rnd(flakeTypes),10));\n"
"        if (allowInactive || i>storm.flakesMaxActive) {\n"
"          storm.flakes[storm.flakes.length-1].active = -1;\n"
"        }\n"
"      }\n"
"      storm.targetElement.appendChild(docFrag);\n"
"    };\n"
"\n"
"    this.timerInit = function() {\n"
"      storm.timer = true;\n"
"      storm.snow();\n"
"    };\n"
"\n"
"    this.init = function() {\n"
"      var i;\n"
"      for (i=0; i<storm.meltFrameCount; i++) {\n"
"        storm.meltFrames.push(1-(i/storm.meltFrameCount));\n"
"      }\n"
"      storm.randomizeWind();\n"
"      storm.createSnow(storm.flakesMax);\n"
"      storm.events.add(window,'resize',storm.resizeHandler);\n"
"      storm.events.add(window,'scroll',storm.scrollHandler);\n"
"      if (storm.freezeOnBlur) {\n"
"        if (isIE) {\n"
"          storm.events.add(document,'focusout',storm.freeze);\n"
"          storm.events.add(document,'focusin',storm.resume);\n"
"        } else {\n"
"          storm.events.add(window,'blur',storm.freeze);\n"
"          storm.events.add(window,'focus',storm.resume);\n"
"        }\n"
"      }\n"
"      storm.resizeHandler();\n"
"      storm.scrollHandler();\n"
"      if (storm.followMouse) {\n"
"        storm.events.add(isIE?document:window,'mousemove',storm.mouseMove);\n"
"      }\n"
"      storm.animationInterval = Math.max(20,storm.animationInterval);\n"
"      storm.timerInit();\n"
"    };\n"
"\n"
"    this.start = function(bFromOnLoad) {\n"
"      if (!didInit) {\n"
"        didInit = true;\n"
"      } else if (bFromOnLoad) {\n"
"        return true;\n"
"      }\n"
"      if (typeof storm.targetElement === 'string') {\n"
"        var targetID = storm.targetElement;\n"
"        storm.targetElement = document.getElementById(targetID);\n"
"        if (!storm.targetElement) {\n"
"          throw new Error('Snowstorm: Unable to get targetElement \"'+targetID+'\"');\n"
"        }\n"
"      }\n"
"      if (!storm.targetElement) {\n"
"        storm.targetElement = (document.body || document.documentElement);\n"
"      }\n"
"      if (storm.targetElement !== document.documentElement && storm.targetElement !== document.body) {\n"
"        storm.resizeHandler = storm.resizeHandlerAlt;\n"
"        storm.usePixelPosition = true;\n"
"      }\n"
"      storm.resizeHandler();\n"
"      storm.usePositionFixed = (storm.usePositionFixed && !noFixed && !storm.flakeBottom);\n"
"      if (window.getComputedStyle) {\n"
"        try {\n"
"          targetElementIsRelative = (window.getComputedStyle(storm.targetElement, null).getPropertyValue('position') === 'relative');\n"
"        } catch(e) {\n"
"          targetElementIsRelative = false;\n"
"        }\n"
"      }\n"
"      fixedForEverything = storm.usePositionFixed;\n"
"      if (screenX && screenY && !storm.disabled) {\n"
"        storm.init();\n"
"        storm.active = true;\n"
"      }\n"
"    };\n"
"\n"
"    function doDelayedStart() {\n"
"      window.setTimeout(function() {\n"
"        storm.start(true);\n"
"      }, 20);\n"
"      storm.events.remove(isIE?document:window,'mousemove',doDelayedStart);\n"
"    }\n"
"\n"
"    function doStart() {\n"
"      if (!storm.excludeMobile || !isMobile) {\n"
"        doDelayedStart();\n"
"      }\n"
"      storm.events.remove(window, 'load', doStart);\n"
"    }\n"
"\n"
"    if (storm.autoStart) {\n"
"      storm.events.add(window, 'load', doStart, false);\n"
"    }\n"
"\n"
"    return this;\n"
"\n"
"  }(window, document));\n"
"\n"
"snowStorm.snowColor = '#ffffff';\n"
"snowStorm.flakesMax = 32;\n"
"snowStorm.flakesMaxActive = 32;\n"
"snowStorm.followMouse = true;\n"
"snowStorm.snowStick = false;\n"
"snowStorm.useMeltEffect = true;\n"
"snowStorm.useTwinkleEffect = true;\n"
"snowStorm.zIndex = 10;\n"
"</script>\n"
"</body>\n"
"</html>\n";

#endif // WEB_DASHBOARD_HTML_H
